### ISSUE TITLE
can't create external table 

### ISSUE THREAD

**Issue by yugandhar47** [arsenvlad/docker-presto-adls-wasb#2]
just followed all steps mentions in READ.ME file . but im getting below error while creating extranal table.
`hive> create table wasbtable2 (name varchar(255)) row format delimited fields terminated by ',' stored as textfile location 'wasb://XXXX@XXXX.blob.core.windows.net/listOfStockSymbol.txt';
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. MetaException(message:Got exception: org.apache.hadoop.fs.azure.AzureException com.microsoft.azure.storage.StorageException: The server encountered an unknown failure: )
hive> `

i updated azure `AZURE_STORAGE_ACCOUNT_NAME=,
AZURE_STORAGE_ACCOUNT_KEY=`
in  `env.conf ` file

**Comment by yugandhar47** [comment]
@arsenvlad

**Comment by arsenvlad** [comment]
Does the blob listOfStockSymbol.txt already exist in that location? Can you try a different location value for your table with a not yet existing file e.g. wasb://container@account.blob.core.windows.net/mytable1 to see if it gets created in the storage account?

**Comment by yugandhar47** [comment]
**Does the blob listOfStockSymbol.txt already exist in that location?** 
yes, it exists.
 **Can you try a different location value for your table with a not yet existing file** 
still throwing `FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. MetaException(message:Got exception: org.apache.hadoop.fs.azure.AzureException com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)`


now im getting 
`FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. MetaException(message:wasbs://xxxx@xxxx.blob.core.windows.net/listOfStockSymbol.txt is not a directory or unable to create one)` error
@arsenvlad

**Comment by arsenvlad** [comment]
I just tested on my end and it works for me...

Are you providing the storage account name and key in the env.conf file or env.conf.private file?
By default, docker-compose.yml is loading environment variables from env.conf.private file which is not checked into Git repro. If you are using env.conf file instead, you will need to update docker-compose.yml to point to that file instead since otherwise the required environment variables are not getting set.

Also, when using create table syntax, the location that you specify must NOT be existent yet. hive will automatically create a file and "folder" in the container for the location you specify. From your 2nd error, it looks like hive tried to create a folder with name "listOfStockSymbol.txt" but it was already there. You should create an empty table using a non-yet existing name like this:

wasbs://xxxx@xxxx.blob.core.windows.net/myfolder

Take a look at the video recording on the top of README.md file where I step through the demo to see if  it maybe can help you spot the difference between what I am doing and what you have.

Please let me know if you find the difference to add it to readme.

Thanks!
